"""
viz_sdf.py
==========
Visualise Signed Distance Field (SDF) .npy files generated by make_sdf.py.

Two modes
---------
Single file
    Display (or save) one SDF with a diverging colour map so that the
    0-boundary is clearly visible as a white iso-line in the centre.

Gallery
    Read every .npy file in a directory and write a thumbnail grid PNG
    that lets you compare many characters at a glance.

Distance convention (from make_sdf.py)
---------------------------------------
  * **Negative** values → inside (ink / glyph interior)  → rendered in blue
  * **Positive** values → outside (background)           → rendered in red
  * **0**               → glyph outline                  → rendered in white

Usage – single file
-------------------
    python scripts/viz_sdf.py out/sdf/U+4E00.npy
    python scripts/viz_sdf.py out/sdf/U+4E00.npy --out preview.png
    python scripts/viz_sdf.py out/sdf/U+4E00.npy --no-contour

Usage – gallery
---------------
    python scripts/viz_sdf.py --gallery out/sdf/
    python scripts/viz_sdf.py --gallery out/sdf/ --out gallery.png
    python scripts/viz_sdf.py --gallery out/sdf/ --cols 20 --thumb 64
    python scripts/viz_sdf.py --gallery out/sdf/ --list lists/joyo.txt

Arguments – single file
-----------------------
file            Path to a .npy SDF file.
--out           Save the figure to this path instead of showing it
                interactively.  Supported formats: png, pdf, svg, …
--clip          Symmetric colour-axis limit (default: auto = max(|SDF|)).
--no-contour    Suppress the 0-iso-line overlay.
--cmap          Matplotlib colormap name (default: RdBu_r).
--title         Figure title (default: file stem).

Arguments – gallery
-------------------
--gallery       Directory containing .npy SDF files.
--list          Optional character list (.txt) to restrict which files are
                shown and to control ordering.
--out           Output PNG path (default: sdf_gallery.png in the SDF dir).
--cols          Number of columns in the grid (default: 16).
--thumb         Thumbnail size in pixels (default: 48).
--cmap          Matplotlib colormap name (default: RdBu_r).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load_sdf(path: Path) -> np.ndarray:
    arr = np.load(path)
    if arr.ndim != 2:
        raise ValueError(f"Expected 2-D array, got shape {arr.shape} in {path}")
    return arr.astype(np.float32)


def _read_char_list(list_path: Path) -> list[str]:
    """Return characters from a one-char-per-line text file."""
    chars = []
    for line in list_path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            chars.append(stripped[0])
    return chars


# ---------------------------------------------------------------------------
# Single-file visualisation
# ---------------------------------------------------------------------------

def visualise_single(
    npy_path: Path,
    *,
    out_path: Path | None = None,
    clip: float | None = None,
    show_contour: bool = True,
    cmap: str = "RdBu_r",
    title: str | None = None,
) -> None:
    """Render one SDF file as a diverging heat-map with an optional 0-contour."""
    sdf = _load_sdf(npy_path)

    vmax = float(clip) if clip is not None else float(np.abs(sdf).max()) or 1.0
    vmin = -vmax

    fig, ax = plt.subplots(figsize=(5, 5))
    im = ax.imshow(sdf, cmap=cmap, vmin=vmin, vmax=vmax, origin="upper")

    if show_contour:
        ax.contour(sdf, levels=[0.0], colors="white", linewidths=1.2)

    fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04, label="distance (px)")

    fig.text(
        0.01, 0.01,
        "Blue = inside (ink)  |  Red = outside  |  White line = glyph outline (SDF = 0)",
        fontsize=7, color="gray", va="bottom",
    )

    ax.set_title(title or npy_path.stem, fontsize=12)
    ax.axis("off")
    fig.tight_layout()

    if out_path is not None:
        fig.savefig(out_path, dpi=150, bbox_inches="tight")
        print(f"Saved: {out_path}")
        plt.close(fig)
    else:
        plt.show()


# ---------------------------------------------------------------------------
# Gallery visualisation
# ---------------------------------------------------------------------------

def visualise_gallery(
    sdf_dir: Path,
    *,
    char_list: list[str] | None = None,
    out_path: Path | None = None,
    cols: int = 16,
    thumb_px: int = 48,
    cmap: str = "RdBu_r",
) -> None:
    """Render a grid of SDF thumbnails for all (or selected) .npy files."""
    if char_list is not None:
        # Ordered by the provided list; skip missing files silently.
        npy_files = []
        labels = []
        for ch in char_list:
            p = sdf_dir / f"U+{ord(ch):04X}.npy"
            if p.exists():
                npy_files.append(p)
                labels.append(ch)
    else:
        npy_files = sorted(sdf_dir.glob("*.npy"))
        labels = [p.stem for p in npy_files]

    if not npy_files:
        sys.exit(f"ERROR: No .npy files found in {sdf_dir}")

    n = len(npy_files)
    rows = (n + cols - 1) // cols

    dpi = 100
    cell_in = thumb_px / dpi  # cell size in inches
    fig_w = cols * cell_in
    fig_h = rows * cell_in

    fig, axes = plt.subplots(
        rows, cols,
        figsize=(fig_w, fig_h),
        squeeze=False,
    )

    # Hide all axes upfront; we'll re-enable used ones.
    for row_axes in axes:
        for ax in row_axes:
            ax.axis("off")

    for idx, (npy_path, label) in enumerate(zip(npy_files, labels)):
        r, c = divmod(idx, cols)
        ax = axes[r][c]
        try:
            sdf = _load_sdf(npy_path)
        except Exception as exc:
            print(f"WARNING: Could not load {npy_path}: {exc}", file=sys.stderr)
            continue

        vmax = float(np.abs(sdf).max()) or 1.0
        ax.imshow(sdf, cmap=cmap, vmin=-vmax, vmax=vmax, origin="upper",
                  interpolation="nearest")
        ax.contour(sdf, levels=[0.0], colors="white", linewidths=0.4)
        ax.set_title(label, fontsize=max(2, thumb_px // 8), pad=1)
        ax.axis("off")

    fig.suptitle(
        "SDF Gallery  –  Blue=inside / Red=outside / White line=outline",
        fontsize=8, y=1.001,
    )
    fig.tight_layout(pad=0.1)

    if out_path is None:
        out_path = sdf_dir / "sdf_gallery.png"

    fig.savefig(out_path, dpi=dpi, bbox_inches="tight")
    print(f"Gallery saved: {out_path}  ({n} characters, {rows}×{cols} grid)")
    plt.close(fig)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Visualise SDF .npy files (single or gallery).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )

    # Positional for single-file mode (optional so gallery mode works too)
    parser.add_argument(
        "file", nargs="?", metavar="FILE",
        help="Path to a single .npy SDF file (single-file mode).",
    )

    # Gallery options
    gal = parser.add_argument_group("gallery mode")
    gal.add_argument(
        "--gallery", metavar="DIR",
        help="Directory of .npy files; activates gallery mode.",
    )
    gal.add_argument(
        "--list", metavar="FILE",
        help="Character list .txt to filter/order gallery entries.",
    )
    gal.add_argument(
        "--cols", type=int, default=16, metavar="N",
        help="Grid columns in gallery (default: 16).",
    )
    gal.add_argument(
        "--thumb", type=int, default=48, metavar="PX",
        help="Thumbnail pixel size (default: 48).",
    )

    # Shared options
    parser.add_argument(
        "--out", metavar="PATH",
        help="Output file path (PNG/PDF/SVG). Omit to show interactively.",
    )
    parser.add_argument(
        "--clip", type=float, default=None, metavar="PX",
        help="Symmetric colour-axis limit (default: auto).",
    )
    parser.add_argument(
        "--no-contour", dest="no_contour", action="store_true",
        help="Suppress the 0-iso-line overlay (single-file mode).",
    )
    parser.add_argument(
        "--cmap", default="RdBu_r", metavar="NAME",
        help="Matplotlib colormap (default: RdBu_r).",
    )
    parser.add_argument(
        "--title", metavar="TEXT",
        help="Figure title (single-file mode; default: file stem).",
    )

    return parser.parse_args()


def main() -> None:
    args = parse_args()

    if args.gallery:
        # ---- Gallery mode ------------------------------------------------
        sdf_dir = Path(args.gallery)
        if not sdf_dir.is_dir():
            sys.exit(f"ERROR: Not a directory: {sdf_dir}")

        char_list: list[str] | None = None
        if args.list:
            list_path = Path(args.list)
            if not list_path.exists():
                sys.exit(f"ERROR: List file not found: {list_path}")
            char_list = _read_char_list(list_path)

        out_path = Path(args.out) if args.out else None

        visualise_gallery(
            sdf_dir,
            char_list=char_list,
            out_path=out_path,
            cols=args.cols,
            thumb_px=args.thumb,
            cmap=args.cmap,
        )

    elif args.file:
        # ---- Single-file mode --------------------------------------------
        npy_path = Path(args.file)
        if not npy_path.exists():
            sys.exit(f"ERROR: File not found: {npy_path}")

        out_path = Path(args.out) if args.out else None

        visualise_single(
            npy_path,
            out_path=out_path,
            clip=args.clip,
            show_contour=not args.no_contour,
            cmap=args.cmap,
            title=args.title,
        )

    else:
        print(
            "ERROR: Specify a .npy file (single mode) or --gallery DIR (gallery mode).",
            file=sys.stderr,
        )
        sys.exit(1)


if __name__ == "__main__":
    main()
